name: Create Release
on:   
  push:
    branches: 
      - main

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: build
        run: make
      - name: get version
        id: get_version
        run: .github/workflows/get_version.sh
      - name: show version
        run: echo ${{steps.get_version.outputs.VERSION}}
      - name: tag repo
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{steps.get_version.outputs.VERSION}}",
              sha: context.sha
            })
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env: 
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{steps.get_version.outputs.VERSION}}
          release_name: Release ${{steps.get_version.outputs.VERSION}}
      - name: Upload RPM
        id: upload-RPM
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.get_version.outputs.FILE}}
          asset_name: ${{ steps.get_version.outputs.FILE}}
          asset_content_type: application/rpm
